// Unique tier names
var TIER_NAMES = [
  "Herald Plank",
  "Sylvan Guardian",
  "Verdant of Wood",
  "BoneFang",
  "Oak Boulder",
  "The Banner Mason",
  "Stone Shaman",
  "The CrystalShard",
  "Green Craig",
  "Fern of Stone",
  "SunHowl",
  "Slate Terra",
  "Slate Astral",
  "The Cosmic Bedrock",
  "Stone Seeker",
  "The LightBane",
  "Ethereal Monolith",
  "Slate Slayer",
  "Legend of Stone",
  "FrostWing",
  "Flint Hero",
  "The Titan Cairn",
  "The MoonHeart",
  "Banner Medal",
  "Bronze Marshal",
  "Herald of Bronze",
  "SilkSword",
  "Brass Emblem",
  "Brass Verdant",
  "The Flame Smelter",
  "Bronze Quake",
  "The FateFang",
  "Boulder Anvil",
  "Brass Quake",
  "Lunar of Bronze",
  "StarOath",
  "Smelted Nova",
  "The Ethereal Armor",
  "Bronze Colossus",
  "The CloudHowl",
  "Cyber Bell",
  "Smelted Engine",
  "Neon of Bronze",
  "IceMaker",
  "Copper Aeon",
  "The Timeless Medal",
  "Bronze Reaper",
  "The DawnWing",
  "Shard Smelter",
  "Anvil Legate",
  "Mesa of Iron",
  "ThunderDancer",
  "Carbon Herald",
  "The Crest Edge",
  "Steel Whelp",
  "The NightSword",
  "Cyclone Rivet",
  "Carbon Rider",
  "Thunder of Steel",
  "DarkFall",
  "Alloy Cliff",
  "The Zephyr Knight",
  "Steel Wing",
  "The SwiftOath",
  "Mistral Blade",
  "Alloy Wing",
  "Zephyr of Steel",
  "IronSight",
  "Tempered Stellar",
  "The Lunar Plate",
  "Steel Wanderer",
  "The RuneMaker",
  "Cosmic Edge",
  "Tempered Wanderer",
  "Lunar of Steel",
  "BoneHold",
  "Hardened Enchanted",
  "The Ethereal Rivet",
  "Steel Oracle",
  "The CrystalDancer",
  "Arcane Knight",
  "Hardened Colossus",
  "Neon of Steel",
  "SunHorn",
  "Steel Royal",
  "The Timeless Blade",
  "Steel Reaper",
  "The LightFall",
  "Sigil Screen",
  "Silver Legate",
  "Banner of Silver",
  "FrostSeeker",
  "Lunar Terra",
  "The Gust Cloud",
  "Silver Seeker",
  "The MoonSight",
  "Ethereal Coin",
  "Lunar Slayer",
  "Legend of Silver",
  "SilkSong",
  "Mercury Pixel",
  "The Regal Shine",
  "Silver Regent",
  "The FateHold",
  "Prism Fang",
  "Mercury Seeker",
  "Herald of Gold",
  "StarWard",
  "Gilded Emblem",
  "The Sigil Coin",
  "Gold Paladin",
  "The CloudHorn",
  "Crest Thread",
  "Gilded Warden",
  "Green of Gold",
  "IceBlade",
  "Gold Fern",
  "The Cyclone Leaf",
  "Gold Tecton",
  "The DawnSeeker",
  "Astral Nugget",
  "Gold Sage",
  "Stellar of Gold",
  "ThunderRider",
  "Golden Cosmic",
  "The Nova Rush",
  "Gold Prophet",
  "The NightSong",
  "Lunar Coin",
  "Golden Prophet",
  "Nova of Gold",
  "DarkVeil",
  "Sunforged Astral",
  "The Cosmic Thread",
  "Gold Seeker",
  "The SwiftWard",
  "Stellar Leaf",
  "Sunforged Seeker",
  "Cosmic of Gold",
  "IronBrand",
  "Aureate Lunar",
  "The Arcane Nugget",
  "Gold Chanter",
  "The RuneBlade",
  "Enchanted Rush",
  "Aureate Chanter",
  "Arcane of Gold",
  "BonePiercer",
  "Gilded Ethereal",
  "The Rune Coin",
  "Gold Seer",
  "The CrystalRider",
  "Legend Thread",
  "Gilded Bane",
  "Hero of Gold",
  "SunRoar",
  "Gold Saga",
  "The Epic Leaf",
  "Gold Engine",
  "The LightVeil",
  "Regal Nugget",
  "Gold Monarch",
  "Crown of Gold",
  "FrostBinder",
  "Golden Royal",
  "The Prince Rush",
  "Gold Majesty",
  "The MoonBrand",
  "Noble Coin",
  "Golden Majesty",
  "Prince of Gold",
  "SilkOmen",
  "Sunforged Chrono",
  "The Aeon Thread",
  "Gold Keeper",
  "The FatePiercer",
  "Eon Leaf",
  "Sunforged Keeper",
  "Jewel of Gold",
  "StarVein",
  "Aureate Shard",
  "The Crystal Nugget",
  "Platinum Marshal",
  "The CloudRoar",
  "Cinder Trophy",
  "Pristine Flow",
  "Tidal of Platinum",
  "IceBreaker",
  "Platinum Cyclone",
  "The Cliff Blond",
  "Platinum Soarer",
  "The DawnBinder",
  "Cosmic Disk",
  "Platinum Wanderer",
  "Lunar of Platinum",
  "ThunderGuard",
  "Noble Nova",
  "The Stellar Grade",
  "Platinum Sage",
  "The NightOmen",
  "Astral Standard",
  "Noble Sage",
  "Ethereal of Platinum",
  "DarkMark",
  "White Mystic",
  "The Enchanted Trophy",
  "Platinum Champion",
  "The SwiftVein",
  "Pixel Blond",
  "White Majesty",
  "Prince of Platinum",
  "IronEdge",
  "Crystal Tidal",
  "The Jewel Eye",
  "Diamond Gleam",
  "The RuneBreaker",
  "Gem Point",
  "Crystal Gleam",
  "Crest of Sapphire",
  "BoneWalker",
  "Cobalt Wave",
  "The Tidal Pool",
  "Sapphire Flow",
  "The CrystalGuard",
  "Current Depths",
  "Cobalt Flow",
  "Tidal of Sapphire",
  "SunCaller",
  "Sapphire Ocean",
  "The Wave Drop",
  "Sapphire Caller",
  "The LightMark",
  "Boulder Star",
  "Sapphire Quake",
  "Cliff of Sapphire",
  "FrostSoul",
  "Deep Nova",
  "The Stellar Lagoon",
  "Sapphire Sage",
  "The MoonEdge",
  "Astral Pool",
  "Deep Sage",
  "Stellar of Sapphire",
  "SilkWind",
  "Azure Cosmic",
  "The Enchanted Depths",
  "Sapphire Binder",
  "The FateWalker",
  "Rune Drop",
  "Azure Champion",
  "Saga of Sapphire",
  "StarBreak",
  "Ocean Titan",
  "The Quantum Star",
  "Sapphire Core",
  "The CloudCaller",
  "Neon Lagoon",
  "Ocean Lord",
  "Jewel of Sapphire",
  "IceShard",
  "Cobalt Shard",
  "The Crystal Pool",
  "Sapphire Seeker",
  "The DawnSoul",
  "Prism Depths",
  "Cobalt Seeker",
  "Crystal of Sapphire",
  "ThunderBane",
  "Sapphire Gem",
  "The Shard Drop",
  "Sapphire Radiance",
  "The NightWind",
  "Jewel Star",
  "Frost Paladin",
  "Green of Ice",
  "DarkHeart",
  "Frozen Current",
  "The Ocean Crystal",
  "Ice Wave",
  "The SwiftBreak",
  "Tidal Borne",
  "Frozen Wave",
  "Ocean of Ice",
  "IronFang",
  "Ice River",
  "The Current Bite",
  "Ice Fury",
  "The RuneShard",
  "Cliff Cap",
  "Ice Tremor",
  "Mesa of Ice",
  "BoneHowl",
  "Permafrost Zephyr",
  "The Gust Flake",
  "Ice Seeker",
  "The CrystalBane",
  "Stellar Crystal",
  "Permafrost Weaver",
  "Mystic of Ice",
  "SunWing",
  "Glacial Rune",
  "The Arcane Borne",
  "Ice Chanter",
  "The LightHeart",
  "Enchanted Bite",
  "Glacial Matrix",
  "Cyber of Ice",
  "FrostSword",
  "Frost Neon",
  "The Pixel Cap",
  "Ice Node",
  "The MoonFang",
  "Jewel Flake",
  "Frost Radiance",
  "Shard of Ice",
  "SilkOath",
  "Frozen Prism",
  "The Gem Crystal",
  "Ice Polisher",
  "The FateHowl",
  "Crystal Borne",
  "Frozen Polisher",
  "Emblem of Emerald",
  "StarMaker",
  "Jade Thorn",
  "The Fern Scepter",
  "Emerald Shaman",
  "The CloudWing",
  "Green Sword",
  "Jade Shaman",
  "Fern of Emerald",
  "IceDancer",
  "Meadow Wild",
  "The Thorn City",
  "Emerald Druid",
  "The DawnSword",
  "Verdant Patch",
  "Meadow Druid",
  "Thorn of Emerald",
  "ThunderFall",
  "Verdant Green",
  "The Wild Isle",
  "Emerald Sprout",
  "The NightOath",
  "Fern Scepter",
  "Verdant Sprout",
  "Wild of Emerald",
  "DarkSight",
  "Emerald Ocean",
  "The Wave Sword",
  "Emerald Diver",
  "The SwiftMaker",
  "Boulder City",
  "Emerald Quake",
  "Sirocco of Emerald",
  "IronHold",
  "Forest Enchanted",
  "The Epic Patch",
  "Emerald Colossus",
  "The RuneDancer",
  "Titan Isle",
  "Forest Engine",
  "Neon of Emerald",
  "BoneHorn",
  "Jade Jewel",
  "The Prism Scepter",
  "Emerald Vein",
  "The CrystalFall",
  "Shard Sword",
  "Crimson Legate",
  "Banner of Ruby",
  "SunSeeker",
  "Blood Wild",
  "The Ember Cross",
  "Ruby Whelp",
  "The LightSight",
  "Inferno Bleed",
  "Blood Whelp",
  "Cosmic of Ruby",
  "FrostSong",
  "Scarlet Rune",
  "The Titan Fury",
  "Ruby Conqueror",
  "The MoonHold",
  "Digital Drop",
  "Scarlet Matrix",
  "Cyber of Ruby",
  "SilkWard",
  "Ruby Gem",
  "The Shard Heart",
  "Ruby Radiance",
  "The FateHorn",
  "Thorn Cluster",
  "Amethyst Warden",
  "Flame of Amethyst",
  "StarBlade",
  "Purple Nova",
  "The Stellar Geode",
  "Amethyst Sage",
  "The CloudSeeker",
  "Astral Haze",
  "Purple Sage",
  "Stellar of Amethyst",
  "IceRider",
  "Violet Cosmic",
  "The Nova Dream",
  "Amethyst Prophet",
  "The DawnSong",
  "Lunar Cavern",
  "Violet Prophet",
  "Nova of Amethyst",
  "ThunderVeil",
  "Mystic Arcane",
  "The Mystic Cluster",
  "Amethyst Weaver",
  "The NightWard",
  "Ethereal Geode",
  "Mystic Weaver",
  "Mystic of Amethyst",
  "DarkBrand",
  "Royal Rune",
  "The Titan Haze",
  "Amethyst Conqueror",
  "The SwiftBlade",
  "Digital Dream",
  "Royal Matrix",
  "Cyber of Amethyst",
  "IronPiercer",
  "Amethyst Neon",
  "The Noble Cavern",
  "The RuneRider",
  "Aeon Cluster",
  "Jewel Cluster",
  "Amethyst Radiance",
  "Shard of Amethyst",
  "BoneRoar",
  "Purple Prism",
  "The Gem Geode",
  "Amethyst Polisher",
  "The CrystalVeil",
  "Crystal Haze",
  "Purple Polisher",
  "Gem of Amethyst",
  "SunBinder",
  "Violet Jewel",
  "The Fern Thorn",
  "Rose Shaman",
  "The LightBrand",
  "Green Garden",
  "Coral Shaman",
  "Fern of Rose",
  "FrostOmen",
  "Petal Wild",
  "The Thorn Bush",
  "Rose Druid",
  "The MoonPiercer",
  "Ocean Bud",
  "Petal Weaver",
  "Quantum of Rose",
  "SilkVein",
  "Black Sigil",
  "The Blaze Tower",
  "Onyx Furnace",
  "The FateRoar",
  "Mesa Gate",
  "Black Voyager",
  "Arcane of Onyx",
  "StarBreaker",
  "Onyx Void",
  "The Umbral Shrine",
  "Onyx Wraith",
  "The CloudBinder",
  "Night Obelisk",
  "Umbral of Onyx",
  "IceGuard",
  "Ebony Abyss",
  "Ebony Prism",
  "The Verdant Hue",
  "Amber Volcan",
  "The DawnOmen",
  "Blaze Light",
  "Golden Volcan",
  "Cyclone of Amber",
  "ThunderMark",
  "Honey Cosmic",
  "The Nova Glow",
  "Amber Prophet",
  "The NightVein",
  "Lunar Beacon",
  "Honey Prophet",
  "Digital of Amber",
  "DarkEdge",
  "Sunstone Regal",
  "The Jewel Grain",
  "Rainbow Druid",
  "The SwiftBreaker",
  "Stellar Mist",
  "Spectrum Seeker",
  "Quantum of Rainbow",
  "IronWalker"
];
